version: "{build}"

os:
  - Visual Studio 2017
  - Visual Studio 2015

branches:
  except:
    - /.*_(doc|dev)$/

init:
  - git config --global core.autocrlf input
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

install:
  - git submodule update --init --recursive

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmake -H. -BBuild -A%PLATFORM%

build:
  project: Build\daleiDB.sln
  parallel: true
  verbosity: normal

test_script:
  - cd Build
  - ctest -V -j 2 -C %CONFIGURATION%
