codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "60...90"

  status:
    project: yes
    patch: yes
    changes: no

ignore:
  - tests
  - utils

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
