language: cpp
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CPPFLAGS="-std=c++17 -Wall -v"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++5.0"
        - CPPFLAGS="-std=c++17 -Wall -v"

before_install:
  - eval "${MATRIX_EVAL}"

script: make run_tests

notifications:
  email:
    on_success: change
    on_failure: always
