language: cpp

branches:
  except:
    - /.*_(doc|dev)$/

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && GCOV=gcov-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: osx

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - cmake --version
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd build
  - make && make test

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make collect_coverage
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
